
// Data for all hero cards
// hero.location options are: "deck", "hand", rowId (e.g. "2m"), "discarded"
// TODO: create test to ensure no cards have anything other than the above values as location
const Heroes = [
  {
    id: "ana",
    name: "Ana",
    image: "assets/heroes/Ana.png",
    icon: "assets/heroes/Ana-icon.png",
    health: 4,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "ashe",
    name: "Ashe",
    image: "assets/heroes/Ashe.png",
    health: 3,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "baptiste",
    name: "Baptiste",
    image: "assets/heroes/Baptiste.png",
    icon: "assets/heroes/Baptiste-icon.png",
    health: 4,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "bastion",
    name: "Bastion",
    image: "assets/heroes/Bastion.png",
    icon: "assets/heroes/Bastion-icon.png",
    health: 5,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "bob",
    name: "Bob",
    image: "assets/heroes/Bob.png",
    icon: "assets/heroes/Bob-icon.png",
    health: 3,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "brigitte",
    name: "Brigitte",
    image: "assets/heroes/Brigitte.png",
    health: 4,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "doomfist",
    name: "Doomfist",
    image: "assets/heroes/Doomfist.png",
    health: 4,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "dvameka",
    name: "D.va + Meka",
    image: "assets/heroes/DvaMeka.png",
    health: 4,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "dva",
    name: "D.va",
    image: "assets/heroes/Dva.png",
    health: 2,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "echo",
    name: "Echo",
    image: "assets/heroes/Echo.png",
    health: 4,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "genji",
    name: "Genji",
    image: "assets/heroes/Genji.png",
    health: 4,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "hanzo",
    name: "Hanzo",
    image: "assets/heroes/Hanzo.png",
    icon: "assets/heroes/Hanzo-icon.png",
    health: 4,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "junkrat",
    name: "Junkrat",
    image: "assets/heroes/Junkrat.png",
    health: 3,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "lucio",
    name: "Lucio",
    image: "assets/heroes/Lucio.png",
    icon: "assets/heroes/Lucio-icon.png",
    health: 3,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "mccree",
    name: "McCree",
    image: "assets/heroes/McCree.png",
    health: 4,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "mei",
    name: "Mei",
    image: "assets/heroes/Mei.png",
    icon: "assets/heroes/Mei-icon.png",
    health: 4,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "mercy",
    name: "Mercy",
    image: "assets/heroes/Mercy.png",
    icon: "assets/heroes/Mercy-icon.png",
    health: 3,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "moira",
    name: "Moira",
    image: "assets/heroes/Moira.png",
    health: 3,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "orisa",
    name: "Orisa",
    image: "assets/heroes/Orisa.png",
    icon: "assets/heroes/Orisa-icon.png",
    health: 5,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "pharah",
    name: "Pharah",
    image: "assets/heroes/Pharah.png",
    health: 4,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "reaper",
    name: "Reaper",
    image: "assets/heroes/Reaper.png",
    health: 4,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "reinhardt",
    name: "Reinhardt",
    image: "assets/heroes/Reinhardt.png",
    health: 4,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "roadhog",
    name: "Roadhog",
    image: "assets/heroes/Roadhog.png",
    health: 5,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "sigma",
    name: "Sigma",
    image: "assets/heroes/Sigma.png",
    icon: "assets/heroes/Sigma-icon.png",
    health: 4,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "soldier",
    name: "Soldier 76",
    image: "assets/heroes/Soldier.png",
    health: 4,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "sombra",
    name: "Sombra",
    image: "assets/heroes/Sombra.png",
    health: 4,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "symmetra",
    name: "Symmetra",
    image: "assets/heroes/Symmetra.png",
    health: 3,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "torbjorn",
    name: "Torbjorn",
    image: "assets/heroes/Torbjorn.png",
    icon: "assets/heroes/Torbjorn-icon.png",
    health: 4,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "tracer",
    name: "Tracer",
    image: "assets/heroes/Tracer.png",
    health: 3,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "widowmaker",
    name: "Widowmaker",
    image: "assets/heroes/Widowmaker.png",
    icon: "assets/heroes/Widowmaker-icon.png",
    health: 4,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "winston",
    name: "Winston",
    image: "assets/heroes/Winston.png",
    health: 4,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "wreckingball",
    name: "Wrecking Ball",
    image: "assets/heroes/WreckingBall.png",
    icon: "assets/heroes/WreckingBall-icon.png",
    health: 3,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "zarya",
    name: "Zarya",
    image: "assets/heroes/Zarya.png",
    icon: "assets/heroes/Zarya-icon.png",
    health: 4,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
  {
    id: "zenyatta",
    name: "Zenyatta",
    image: "assets/heroes/Zenyatta.png",
    icon: "assets/heroes/Zenyatta-icon.png",
    health: 4,
    ability1: () => {},
    ability2: () => {},
    player1location: "deck",
    player2location: "deck",
  },
];

export default Heroes;
